In [1]:
import pickle 
import numpy as np 

In [2]:
ohe_sex = pickle.load(open('ohe_sex.pkl' , 'rb') )
ohe_embark = pickle.load(open('ohe_embark.pkl' , 'rb'))
dTC = pickle.load(open('dTC.pkl' , 'rb'))

	Pclass	Sex	Age	SibSp	Parch	Fare	Embarked

In [4]:
list = [2,'female' , 58.9 , 3, 2 , 65.88338 , 'S'],

In [6]:
np.array(list).dtype

dtype('<U32')

In [3]:
test = np.array([2,'female' , 58.9 , 3, 2 , 65.88338 , 'S'], dtype = object)

In [9]:
test.shape

(7,)

In [11]:
t_i = test.reshape(1 ,7)

In [12]:
t_i.shape

(1, 7)

In [13]:
t_i

array([[2, 'female', 58.9, 3, 2, 65.88338, 'S']], dtype=object)

In [14]:
test_sex = ohe_sex.transform(t_i[: , 1].reshape(1,1))

c:\Users\gulshan\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [17]:
test_embark = ohe_embark.transform(t_i[: , -1].reshape(1,1))

c:\Users\gulshan\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [19]:
test_embark.shape

(1, 4)

In [20]:
test_age = t_i[:,2].reshape(1,1)

In [21]:
test_age

array([[58.9]], dtype=object)

In [22]:
test_transform = np.concatenate((t_i[: , [0,3,4,5]], test_age , test_sex ,test_embark) , axis = 1)

In [23]:
test_transform.shape

(1, 11)

In [24]:
dTC.predict(test_transform)

array([1])

In [25]:
dTC.predict_proba(test_transform)

array([[0., 1.]])

In [26]:
dTC.predict_log_proba(test_transform)

c:\Users\gulshan\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\tree\_classes.py:1092: RuntimeWarning: divide by zero encountered in log
  return np.log(proba)


array([[-inf,   0.]])

Conclusion  : Means that our patient would surive